version: '3.9'
services:
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-db
    hostname: postgres-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=quotation_freight
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d

  liquibase:
    image: liquibase/liquibase:latest
    volumes:
      - ../../src/main/resources/db/changelog:/liquibase/changelog
    command: --driver=org.postgresql.Driver --url="jdbc:postgresql://postgres-db:5432/quotation_freight" --changeLogFile=../../src/main/resources/db/changelog/db.changelog-master.xml --username=local --password=local --logLevel=info update
    depends_on:
      - postgres-db

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.2.1
    container_name: quotation-freight-broker
    hostname: kafka
    restart: always
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1

  schemaregistry:
    image: confluentinc/cp-schema-registry:6.2.1
    container_name: schema-registry
    restart: always
    depends_on:
      - broker
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8085"
    ports:
      - 8085:8085

  kowl:
    image: quay.io/cloudhut/kowl:master
    container_name: kowl
    hostname: kowl
    restart: on-failure
    ports:
      - "9094:8080"
    environment:
      KAFKA_BROKERS: "kafka:29092"
      KAFKA_SCHEMAREGISTRY_ENABLED: "true"
      KAFKA_SCHEMAREGISTRY_URLS: http://schemaregistry:8085
    depends_on:
      - schemaregistry